services:
  - type: web
    name: terabox-vault-backend
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: MASTER_KEY
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
